create static UI
ktb-eatbook/eatbook-backoffice-frontend pull request #1
Opened 2024-10-31 08:23 UTC by jeong617

## 작업사항

아래 페이지들 정적 ui 제작

<img width="1512" alt="홈페이지" src="https://github.com/user-attachments/assets/8dad4c4f-33d3-4116-a199-9e00e7d2ff1f">
<img width="1512" alt="회원 관리 페이지" src="https://github.com/user-attachments/assets/d5534cd1-9c30-43fe-9b3c-9f5a49fbead9">
<img width="1512" alt="통계 페이지" src="https://github.com/user-attachments/assets/55acc71d-3a64-4671-b1a8-89771d9be361">
<img width="1512" alt="새작품 추가" src="https://github.com/user-attachments/assets/3b46ef2b-0909-4a62-94a1-460d1a00bea1">
<img width="1512" alt="새 에피소드 업로드" src="https://github.com/user-attachments/assets/becc686c-f1ca-4919-9d96-b5097f5c49a7">
<img width="1512
<img width="1512" alt="도서 상세 페이지" src="https://github.com/user-attachments/assets/c84b0909-8cdf-4024-bf5f-b83e6113bab6">
" alt="도서 상세-댓글탭" src="https://github.com/user-attachments/assets/6e716c99-1d99-40c4-bb3b-73ca1e2184ef">
<img width="1512" alt="도서 상세 페이지" src="https://github.com/user-attachments/assets/48c2b6c9-37ea-4d64-ab55-d3d02adddfef">
<img width="1512" alt="기존 작품 수정" src="https://github.com/user-attachments/assets/44a024a7-bf0c-4511-9e72-075771ea451d">
<img width="1512" alt="검색 결과" src="https://github.com/user-attachments/assets/be97d057-c1ba-47ec-a28d-2e53b2f5a1a0">

## 관련 이슈
\
추후
라우팅으로 react-router-dom,
상태관리로 zustand
api 통신용으로 axios
와 같은 라이브러리를 이용한 기능들이 추가될 예정입니다.

## 중점적으로 봐줬으면 하는 부분 (선택 사항)

ui 평가 전체적으로 한번만 부탁드립니다! ex. 디자인 이거 별로다, 이 버튼 빠졌다 등등..

2024-10-31 15:15 UTC, cjm0611 commented
UI 전체적으로 깔끔하고 통일성 있어서 좋은 것 같습니다!! 👍
아래 부분은 전체적인 UI 평가 부탁하셔서 페이지별로 수정사항 정리했습니다.
@ 붙어있는 건 질문입니다!


[대시보드]
- “DASHBOARD”라는 글자와 데이터 통계 테이블의 양쪽 여백을 통일하여 테이블 좌측 상단에 글자가 오도록 배치

<br />

[도서 정보 입력 페이지]
- 저장 버튼을 중앙 상단에서 우측 상단으로 이동 (다른 페이지와의 UI 통일)
- 상세 정보 입력란의 형태 변경 - 입력 데이터의 길이가 길어질 수 있음. 여러 줄을 동시에 확인할 수 있도록 text 필드를 쓰는 등의 형식 변경이 필요 (Figma처럼)
- 줄거리, 출판년도, 완결 여부 입력 칸 필요

- @ 상세 정보가 줄거리인가요?
- @ 저자 여러명 입력가능한데 이 부분 input 필드에서 어떻게 입력받나요?
- @ 일부 UI 미완성 부분(표지 등록 아이콘이랑 카테고리 정보 입력란) => 이건 데이터 연결하면서 작업하려고 일부러 빼신 걸까요?

<br />

[소설 관리 페이지]
- 회차 정보 / 댓글 두개의 탭 중, 현재 선택한 탭에 underline을 넣거나 하여 현재 선택한 탭을 표시

2024-10-31 16:02 UTC, cjm0611 requested changes

2024-10-31 16:02 UTC, cjm0611 commented on src/components/CommentItem.tsx
> +    created_at: string;
camelCase로 변경 부탁드려요. `createdAt`

2024-10-31 16:02 UTC, cjm0611 commented on src/components/StatsListItem.tsx
> +type DisplayType = "view" | "like" | "comment" | "bookmark";
enum type으로 변경하면 좋을 것 같습니다.
```ts
enum DisplayType {
  View = "view",
  Like = "like",
  Comment = "comment",
  Bookmark = "bookmark",
}
```

2024-10-31 16:02 UTC, cjm0611 commented on src/pages/DashBoard.tsx
> +                                                                                 data={1234} rank={5}/></li>
이후에 데이터 연결하시면서 해당 list부분 별도의 컴포넌트로 추출하고, 상위 컴포넌트에서는 배열로 관리하도록 변경 부탁드립니다!
예시:
```ts
<ul className="divide-y divide-gray-200">
        {items.map((item) => (
          <li key={item.rank} className="py-3 sm:py-4">
            <StatsListItem
              title={item.title}
              author={item.author}
              display={displayType}
              data={item.data}
              rank={item.rank}
            />
          </li>
        ))}
      </ul>
```

2024-10-31 16:02 UTC, cjm0611 commented on src/pages/ManageMembers.tsx
> +type TabType = "admins" | "members";
enum type으로 변경 부탁드립니다!

2024-10-31 16:02 UTC, cjm0611 commented on src/pages/ManageMembers.tsx
> +                            className="rounded-b-normal-radius"
이 부분도 이후에 데이터 연결하면서 배열로 관리되게끔 변경 부탁드립니다.

2024-10-31 16:02 UTC, cjm0611 commented on src/pages/SearchResult.tsx
> +type SortType = "latest" | "alphabetical";
마찬가지로 enum type으로 변경부탁드립니다.
enum 타입들을 src/types/... 폴더 안에 모아서 정의내리고 이걸 각 컴포넌트에서 import해서 쓰면 어떨까요?
모든 타입을 한 곳에 모아두면 어떤 타입들이 존재하는지 쉽게 파악할 수 있고, 타입들이 모여 있어 코드의 전체적인 구조와 가독성이 향상될 것 같습니다.

2024-10-31 16:02 UTC, cjm0611 commented on src/pages/book/BookDetail.tsx
> +type TapType = "episodes" | "comments";
마찬가지로 enum type으로 변경부탁드립니다.

2024-10-31 16:02 UTC, cjm0611 commented on src/pages/form/AddBook.tsx
> +    if (isOpend) {
if-else문 보다는 && 조건식을 이용하면  코드가 더 짧아지고 직관적으로 표현된다고 생각하는데 어떠신가요?
```ts
return isOpend && (
    <div className="fixed inset-0 bg-black bg-opacity-20 flex justify-center items-center">
      <div className="flex flex-col gap-5 bg-white w-[800px] p-6 rounded-md shadow-lg">
        {/* 저장 버튼 */}
        <MainButton className="w-14 self-end" label="저장" />

        {/* 표지 등록 */}
        <div className="flex flex-row">
          <h2 className="w-[250px] ml-3 text-lg font-bold">표지 등록</h2>
          <span className="flex justify-center items-center rounded-normal-radius w-28 h-32 bg-background">
            <AiOutlineUpload size={40} />
          </span>
        </div>

        {/* 도서 정보 */}
        <div className="flex flex-row">
          <h2 className="w-[250px] ml-3 text-lg font-bold">도서 정보</h2>
          <div className="flex flex-col gap-2.5 w-96">
            <InputBox label="책 제목" />
            <InputBox label="저자" />
            <InputBox label="상세 정보" rows={4} />
          </div>
        </div>

        {/* 카테고리 */}
        <div className="flex flex-row pb-3">
          <h2 className="w-[250px] ml-3 text-lg font-bold">카테고리</h2>
          <div className="flex flex-wrap w-96 gap-3">
            {categories.map((category) => (
              <SelectChip key={category} value={category} isActivated={false} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
```

2024-10-31 16:15 UTC, cjm0611 commented
추가로 두 가지 제안을 드리고 싶습니다!

1. 현재 prettier 설정이 없는 것 같아 코드 포맷팅 툴을 추가해 주시면 좋을 것 같습니다.
2. Airbnb 스타일 가이드를 도입하면 어떨까요?
유명한 스타일 가이드를 적용하면 코드 가독성이 높아지고 유지보수가 쉬워진다는 장점이 있다고 생각합니다. Airbnb 혹은 구글 자바스크립트 컨벤션 등 하나를 골라 적용하면 어떨까요? 만약 Airbnb 스타일을 적용한다면 전체적으로 크게 2가지 변경 사항이 있을 것 같습니다.
- function 대신 const와 화살표 함수를 사용
- 파라미터 정의 시 공백 추가 `{ chapter, nickname, comment, created_at }: CommentItemProps`

적용 여부는 crystal께서 편하신 방향으로 결정해주시면 감사하겠습니다.

2024-11-01 12:20 UTC, jeong617 commented on src/pages/DashBoard.tsx
> +                                                                                 data={1234} rank={5}/></li>
api 코드 작성하면서 mockdata 파일을 함께 만들 것 같습니다. 임시데이터 만들어지면 그걸로 map 돌려볼 예정입니다!

2024-11-01 12:26 UTC, jeong617 commented on src/pages/SearchResult.tsx
> +type SortType = "latest" | "alphabetical";
이 부분은 상태관리 코드 짤 때 함께 반영하게 될 것 같습니다!

2024-11-01 12:51 UTC, jeong617 commented
제안 주신 코드 포맷팅 툴을 도입하려고 했으나, 계속 설정할 때 충돌이 나서 찾아보니 최근 Eslint 업데이트로인해 관련 이슈가 많아보이더라구요.. 이건 도입하려면 시간이 꽤나 걸릴 것 같아서 일단 보류해두고 있겠습니다...!
아마 추천해주신 airbnb 포맷팅에서 큼직한 룰 정도만 선택해서 수동으로 맞출 것 같아요
코드리뷰 꼼꼼하게 해주셔서 정말 감사합니다!!!

2024-11-04 01:28 UTC, jeong617 commented
### 질문에 대한 답변입니다
- 상세정보가 줄거리입니다! 좀 헷갈리는 요소이면 아예 줄거리로 바꿔둘까요?
- 저자 정보 입력란에 + 버튼 추가해서 아이콘 추가해뒀습니다. 추후 onClick함수 연결해두겠습니다.
- 저거 로딩 덜 된 화면이 스크릿샷으로 들어간 것 같네요..? 정상적인 화면은 첨부된 이미지와 같습니다.
<img width="1512" alt="스크린샷 2024-11-04 오전 10 17 45" src="https://github.com/user-attachments/assets/97adcdfc-d9e2-493e-9061-c23708ade697">

### 수정사항에 대한 코멘트입니다
- 도서 상세 정보 페이지에서 underline 반영했습니다
- dashboard 여백 통일했습니다.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/3b8e5502-abd0-43f7-b9f5-d13c7bbba6a8">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/b846a54d-bf9f-4068-9408-90db8c84b88d">

2024-11-04 02:33 UTC, cjm0611 commented
통일성을 위해 "상세 정보" 보다 "줄거리"로 표시하는게 좋을 것 같습니다.
DASHBOARD 글자 여백은 수정 사항이 잘못 전달된 듯 하여 구두로 전달드리겠습니다!

2024-11-04 02:35 UTC, cjm0611 commented
구두 회의 결과: DASHBOARD는 현재 스타일 유지하기로 결정

2024-11-04 02:35 UTC, cjm0611 approved these changes

2024-11-04 02:48 UTC, merged