[feat/EATBOOK-107] API 연동 코드 추가
ktb-eatbook/eatbook-backoffice-frontend pull request #3
Opened 2024-11-12 08:07 UTC by jeong617

# API 연동 코드 추가

## 작업사항

다음 api들과 통신하는 코드가 추가되었습니다.
- 새 작품 생성요청
- 에피소드 업로드 요청
- 소설 리스트 조회 요청
- 소설 상세정보 조회 요청

## 관련 이슈

급하게 짜면서 미흡한 부분이 많습니다. 예를 들어
- 타입 선언 없이 동작하는 코드
- 하드코딩되어 중복인 코드
연장된 스프린트 기간이 끝날 때까지 이런 부분들을 리팩토링 예정입니다.

## 중점적으로 봐줬으면 하는 부분

타입선언 안되어있는 부분은 전체적으로 체크할 예정이어서, 이 부분보다는
- 너무 하드코딩 되어있는 부분이 있는지
- 구조적으로 더 좋게 바꿀수 있는 부분이 있을지

에 대하여 의견(혹은 신랄한 비판)주시면 감사하겠습니다!

2024-11-12 09:14 UTC, cjm0611 requested changes

2024-11-12 09:14 UTC, cjm0611 commented on package.json
> -    "eslint-config-airbnb": "^19.0.4",
이거 제거하신 이유가 따로 있나요?

2024-11-12 09:14 UTC, cjm0611 commented on src/components/FormButton.tsx
> -        <button className="h-[40px] bg-main rounded-normal-radius shadow-md flex-col justify-center items-center inline-flex">
컴포넌트 이름이 `FormButton`인 만큼 태그는 button으로 유지하면 좋을 것 같습니다! button 태그 안에 div 태그가 들어가는 것은 span 태그로 대체하여 작성함으로써 해결하면 어떨까요?

2024-11-12 09:14 UTC, cjm0611 commented on src/components/SimpleBookCard.tsx
> +                     target.src = defaultImage;
해당 부분 별도 함수로 추출해주세요!

2024-11-12 09:14 UTC, cjm0611 commented on src/components/header/index.tsx
> +        ><FaBars size={18} className="fill-button-text" /></button>
여기 태그 depth 수정해주세요! 가독성이 많이 떨어집니다.

```js
<button onClick={toggle}>
    <FaBars size={18} className="fill-button-text" />
</button>
```

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/Home.tsx
> +          {Array.isArray(novelList) && novelList.length > 0 ? (
`Array.isArray(novelList) && novelList.length > 0`이 조건 별도의 변수로 추출하면 어떤 조건을 확인하는 건지 명확할 것 같습니다.
e.g. `const isNovelListNonEmpty = Array.isArray(novelList) && novelList.length > 0;`

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/Home.tsx
> +            totalPages={10}
총 페이지 수는 나중에 API 연동하면서 수정하는 건가요? 해당 컴포넌트에서 소설 리스트를 받아오는 API는 연동이 되어있는 것처럼 보이는데, 페이지네이션 정보를 받아오는 API는 별개인가요?

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/form/AddBook.tsx
> +  console.log(bookData.category);
`console.log`는 프로덕션 환경에서도 로그를 노출할 수 있는 위험이 있습니다. 콘솔에 꼭 표시되어야 하는 정보가 아니라, 개발 과정에서 필요한 로그라면 `console.debug`를 사용해주세요.

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/form/AddBook.tsx
> +          console.log(presignedUrl);
위와 동일합니다.

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/form/AddBook.tsx
> +                  console.log('File uploaded successfully', uploadRes);
위와 동일합니다.

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/form/AddBook.tsx
> +          const presignedUrl = res.data.presignedUrl;
여유가 된다면, Presigned URL 요청 함수를 분리해주세요.
예시(플로우만 봐주세요!):
```js
// Presigned URL 요청 함수
const createPresignedUrl = async (data: any): Promise<PresignedUrlResponse> => {
  try {
      const response = await post<PresignedUrlResponse>({
          url: 'api/admin/episode',
          data,
      });
      return response.data;
  } catch (error) {
      console.error('Error creating presignedURL:', error);
      throw error;
  }
};
```

```js
try {
      // Presigned URL 생성
      const presignedResponse = await createPresignedUrl({ ...episodeData, novelId });
      const presignedUrl = presignedResponse.presignedUrl;

        // 파일 업로드
        if (file && presignedUrl) {
            const uploadResponse = await uploadFile(presignedUrl, file);
            alert('업로드 성공!');
        } else {
            console.warn('파일이나 Presigned URL이 없습니다.');
            alert('파일이나 업로드 URL이 없습니다.');
        }
    } catch (error) {
        console.error('Error during submission:', error);
        alert('에피소드 생성 또는 파일 업로드 중 오류가 발생했습니다.');
    } finally {
        setIsSubmitting(false); // 제출 상태 종료
    }
```

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/form/UploadEpisode.tsx
> +            });
위와 마찬가지로 presignedUrl 호출을 위한 API 함수를 구분하면 코드 가독성이 올라갈 것 같습니다.
Book(소설) 업로드랑 에피소드 업로드 로직이 비슷한데 별도의 util 함수로 분리하면 어떨까요?

2024-11-12 09:14 UTC, cjm0611 commented on src/pages/form/UploadEpisode.tsx
> +        console.log(episodeData);
위와 동일합니다.

2024-11-13 02:32 UTC, jeong617 commented on package.json
> -    "eslint-config-airbnb": "^19.0.4",
eslint랑 prettier로 코드 스타일 가이드 적용하려고 했었는데, eslint 업데이트 이후로 충돌 사항이 계속 해결이 안되더라구요
그래서 아예 빼버렸습니다..

2024-11-13 03:55 UTC, jeong617 commented on src/pages/Home.tsx
> +            totalPages={10}
아 저부분은 맨밑에 페이지네이션에 아직 onClick event가 안걸려있어서 그거 걸면서 current page 상태관리 같이 할 예정입니다!

2024-11-15 04:44 UTC, jeong617 commented
console.log 밭을 만들어놨었네요. 안 좋은 습관인데 계속 고쳐나가보겠습니다🥲
상세한 코드리뷰 정말 감사합니다!!
구두로 잠깐 말해주신 것처럼 디벨롭 브랜치를 새로 파놔서, 거기에 부으려고 합니다.
휴가동안 잘 충전하시고, 다음주에 뵙겠습니다!!

2024-11-15 06:41 UTC, cjm0611 commented on package.json
> -    "eslint-config-airbnb": "^19.0.4",
prettier는 적용되어 있으니 우선 개발 진행하고, 시간될 때 같이 원인 찾아봅시다!

2024-11-15 06:41 UTC, cjm0611 approved these changes

2024-11-15 06:41 UTC, merged