[feat/EATBOOK-118] 홈화면 pagination 적용
ktb-eatbook/eatbook-backoffice-frontend pull request #7
Opened 2024-11-19 01:10 UTC by jeong617

# 홈화면 Pagination적용

## 작업사항

- 페이지 번호 클릭시, 바뀐 currentPage에 대해 get api 요청으로 받아온 소설 리스트를 띄워줍니다.

## 관련 이슈

- 추후 고도화 단계에서 이미지 최적화에 대한 코드가 추가될 수 있습니다.
- loading상태일 때의 UI가 아직 구현되어있지 않습니다.

## 참고사항
- 에피소드 & 댓글리스트 mock데이터랑 연동해보는 코드가 좀 섞여있습니다. 실제 데이터 형식과 꽤 다를 수 있어서 이부분은 무시해주세요! (추후 api 연동 브랜치 pr에서 봐주시면 감사하겠습니다)

2024-11-19 02:20 UTC, cjm0611 requested changes

2024-11-19 02:20 UTC, cjm0611 commented on src/pages/Home.tsx
> +  // etc.
주석에 적을 내용 없으면 주석 제거하는 게 좋을 것 같습니다!

2024-11-19 02:20 UTC, cjm0611 commented on src/pages/Home.tsx
> +  }, [pageInfo.currentPage]);
가독성을 위해 비동기 함수를 별도로 분리해서 작성하면 좋을 것 같아요!

```js
useEffect(() => {
  const fetchNovelList = async () => {
    try {
      const res = await get({
        url: `api/admin/novel/list?page=${pageInfo.currentPage}&size=20`,
      });
      setNovelList(res.data.data.novelList);
      setPageInfo((prev) => ({
        ...prev,
        totalPages: res.data.data.totalPages,
        totalElements: res.data.data.totalElements,
      }));
    } catch (error) {
      console.error('소설 목록을 가져오는 데 실패했습니다.', error);
    }
  };

  fetchNovelList();
}, [pageInfo.currentPage]);
```

2024-11-19 02:25 UTC, jeong617 commented on src/pages/Home.tsx
> +  // etc.
이거 안지웠네요 ㅋㅋㅋㅋㅋㅋ 민망해라 지워두겠습니다!

2024-11-21 00:17 UTC, cjm0611 approved these changes

2024-11-21 00:26 UTC, merged